### ISSUE TITLE
로그인후 로그아웃버튼이 제대로 동작하지 않는 문제

### ISSUE THREAD

**Issue by 4ramin** [exuscms/ExusCMS#6]
로그인후 검색창 옆에있는 로그아웃 버튼이 제대로 먹히지 않습니다.
그리고 로그아웃 버튼을 상단에 표시하기 보다는 아까도 건의했듯 닉네임 밑에 집어넣는건 어떨지요?

**Comment by exuscms** [comment]
네, 닉네임 옆에도 로그아웃 버튼을 넣도록 하겠습니다. 감사합니다.

**Comment by exuscms** [comment]
#16 자바스크립트 ES6 미지원으로 인한 로그인 오류
#16과 같이 묶어서 처리
닉네임 옆에 로그아웃 버튼 삽입 완료
